name: Release Packages

on:
  push:
    branches:
      - main
    tags:
      - '*'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # 2.32.0
        with:
          php-version: '8.2'
          extensions: mbstring, xml, soap
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist
      - name: Run tests
        run: php test.php

  release_packages:
    needs: tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        package:
          - geojson-reproject
          - pulp
          - pulp-concert
          - pulp-geocsv
          - pulp-geojson
          - pulp-json
          - pulp-soap
          - pulp-tic
          - pulp-xml

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Split and Push ${{ matrix.package }}
        uses: danharrin/monorepo-split-github-action@14e42e2437f674b8987c1f50ca3689116aea1893 # v2.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: 'packages/${{ matrix.package }}'
          repository_organization: 'mapsight'
          repository_name: '${{ matrix.package }}'
          # split-repository-host: "github.com" # Optional: defaults to github.com
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          branch: "main"
